apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feed
  description: Сервис ленты
  annotations:
    github.com/project-slug: s21platform/feed-service
  tags:
    - grpc
    - kafka
    - postgres
  links:
    - url: https://metric.x.space-21.ru/d/ce3mgzcz0b668a/avatar-service?orgId=1 # todo заменить на нашу
      title: Grafana
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: feed-service-team
  providesApis:
    - CreateUserPost

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CreateUserPost
  description: получение uuid нового поста
  annotations:
    github.com/project-slug: s21platform/feed-service
  tags:
    - proto
spec:
  type: grpc
  lifecycle: production
  owner: feed-service-team
  definition: |
    rpc CreateUserPost(CreateUserPostIn) returns (CreateUserPostOut){};
    
    message CreateUserPostIn {
      string content = 1;
    }
      
    message CreateUserPostOut {
      string post_uuid = 1;
    }
