// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserPostIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserPostIn) Reset() {
	*x = CreateUserPostIn{}
	mi := &file_api_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserPostIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserPostIn) ProtoMessage() {}

func (x *CreateUserPostIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserPostIn.ProtoReflect.Descriptor instead.
func (*CreateUserPostIn) Descriptor() ([]byte, []int) {
	return file_api_feed_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserPostIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateUserPostOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserPostOut) Reset() {
	*x = CreateUserPostOut{}
	mi := &file_api_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserPostOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserPostOut) ProtoMessage() {}

func (x *CreateUserPostOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserPostOut.ProtoReflect.Descriptor instead.
func (*CreateUserPostOut) Descriptor() ([]byte, []int) {
	return file_api_feed_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserPostOut) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

var File_api_feed_proto protoreflect.FileDescriptor

const file_api_feed_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/feed.proto\",\n" +
	"\x10CreateUserPostIn\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"0\n" +
	"\x11CreateUserPostOut\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid2H\n" +
	"\vFeedService\x129\n" +
	"\x0eCreateUserPost\x12\x11.CreateUserPostIn\x1a\x12.CreateUserPostOut\"\x00B\n" +
	"Z\bpkg/feedb\x06proto3"

var (
	file_api_feed_proto_rawDescOnce sync.Once
	file_api_feed_proto_rawDescData []byte
)

func file_api_feed_proto_rawDescGZIP() []byte {
	file_api_feed_proto_rawDescOnce.Do(func() {
		file_api_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_feed_proto_rawDesc), len(file_api_feed_proto_rawDesc)))
	})
	return file_api_feed_proto_rawDescData
}

var file_api_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_feed_proto_goTypes = []any{
	(*CreateUserPostIn)(nil),  // 0: CreateUserPostIn
	(*CreateUserPostOut)(nil), // 1: CreateUserPostOut
}
var file_api_feed_proto_depIdxs = []int32{
	0, // 0: FeedService.CreateUserPost:input_type -> CreateUserPostIn
	1, // 1: FeedService.CreateUserPost:output_type -> CreateUserPostOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_feed_proto_init() }
func file_api_feed_proto_init() {
	if File_api_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_feed_proto_rawDesc), len(file_api_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_feed_proto_goTypes,
		DependencyIndexes: file_api_feed_proto_depIdxs,
		MessageInfos:      file_api_feed_proto_msgTypes,
	}.Build()
	File_api_feed_proto = out.File
	file_api_feed_proto_goTypes = nil
	file_api_feed_proto_depIdxs = nil
}
